name: Testing with Pytest - Workflow For HW1 CSC510  

on:
  push: #trigger to allow the workflow to run on push/commit to all branches
  pull_request: #trigger to allow the workflow to run on all created pull requests

jobs:
  run-tests:
    strategy:
      fail-fast: false # fail-fast==false Strategy dictates that if one action fails, all other strategies won't cascade-fail. By setting this, we can see which versions and which operating systems are failing.
      matrix:
        os: [ubuntu, windows, macos] # Labels copied from https://github.com/actions/runner-images
        python-version: ["3.11","3.12","3.13"] #you can add other python versions you would like to test with in this list. #List of python versions: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
    
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 #performs set of actions provided by github at https://github.com/actions/checkout (v4 is latest version as of time of writing this)
      
    - name: Setup Python
      uses: actions/setup-python@v5  #performs set of actions provided by github at https://github.com/actions/setup-python (v5 is latest version as of time of writing this)
      with:
        python-version: ${{ matrix.python-version }} #sets up all the python versions mentioned in the `python-version` variable set above in `matrix`
        allow-prereleases: true #check out https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases
      
    - name: Install Dependencies
      run: |  
        python -m pip install --upgrade pip  
        pip install -r requirements_dev.txt

    - name: Test with pytest  
      run: |  
        coverage run -m pytest -v -s
      continue-on-error: true  
      
    - name: Generate Coverage Report  
      run: |  
        coverage report -m
